#!/usr/bin/env python3
"""Create a disposable Git repository for exercising the Forkstack UI.

The generated graph is:

    main-1--main-2--main-3--main-4--main-5--main-6
                         |                         |--beta-1--beta-2--beta-3
                         |--alpha-1--alpha-2--alpha-3
                                                   |--gamma-1--gamma-2--gamma-3

Each stack commit has an ``fs-branch`` trailer plus matching local and remote
``fs-head`` refs. Remote ``fs-base`` refs reproduce the layout made by
``forkstack submit --execute``.
"""

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import tempfile
from pathlib import Path


MARKER = ".forkstack-fixture"
DEFAULT_FIXTURE = Path(tempfile.gettempdir()) / f"forkstack-fixture-{os.getuid()}"


def git(repo: Path, *args: str, input: str | None = None) -> str:
    return subprocess.run(
        ["git", *args],
        cwd=repo,
        check=True,
        text=True,
        capture_output=True,
        input=input,
    ).stdout.strip()


def _append_data(stream: bytearray, value: str) -> None:
    encoded = value.encode()
    stream.extend(f"data {len(encoded)}\n".encode())
    stream.extend(encoded)
    stream.extend(b"\n")


def _append_commit(
    stream: bytearray,
    *,
    ref: str,
    mark: int,
    parent: int | None,
    filename: str,
    subject: str,
    identity: str | None = None,
) -> None:
    message = subject
    if identity is not None:
        message += f"\n\nfs-branch: {identity}"
    timestamp = 1_700_000_000 + mark

    stream.extend(f"commit refs/heads/{ref}\n".encode())
    stream.extend(f"mark :{mark}\n".encode())
    stream.extend(
        f"author Forkstack Fixture <fixture@example.com> {timestamp} +0000\n".encode()
    )
    stream.extend(
        f"committer Forkstack Fixture <fixture@example.com> {timestamp} +0000\n".encode()
    )
    _append_data(stream, message)
    if parent is not None:
        stream.extend(f"from :{parent}\n".encode())
    stream.extend(f"M 100644 inline {filename}\n".encode())
    _append_data(stream, f"{subject}\n")


def _append_reset(stream: bytearray, ref: str, mark: int) -> None:
    stream.extend(f"reset {ref}\nfrom :{mark}\n\n".encode())


def fixture_stream() -> bytes:
    """Build the whole fixture graph for one ``git fast-import`` process."""
    stream = bytearray()

    parent = None
    for mark in range(1, 7):
        _append_commit(
            stream,
            ref="main",
            mark=mark,
            parent=parent,
            filename=f"main-{mark}.txt",
            subject=f"Main change {mark}",
        )
        parent = mark

    stacks = (
        ("alpha", 3, 7),
        ("beta", 6, 10),
        ("gamma", 9, 13),
    )
    for name, base_mark, first_mark in stacks:
        parent = base_mark
        for number in range(1, 4):
            mark = first_mark + number - 1
            identity = f"{name}/{number}"
            _append_commit(
                stream,
                ref=f"fs-head/{identity}",
                mark=mark,
                parent=parent,
                filename=f"{name}-{number}.txt",
                subject=f"{name.title()} change {number}",
                identity=identity,
            )
            _append_reset(stream, f"refs/remotes/origin/fs-head/{identity}", mark)
            _append_reset(stream, f"refs/remotes/origin/fs-base/{identity}", parent)
            parent = mark

    _append_reset(stream, "refs/remotes/origin/main", 6)
    stream.extend(b"done\n")
    return bytes(stream)


def create_fixture(root: Path, force: bool = False) -> Path:
    root = root.resolve()
    if root.exists():
        if not force:
            raise RuntimeError(f"{root} already exists; pass --force to recreate it")
        if not (root / MARKER).is_file():
            raise RuntimeError(f"refusing to remove {root}: fixture marker is missing")
        shutil.rmtree(root)

    root.mkdir(parents=True)
    (root / MARKER).write_text("generated by create_fixture_repo.py\n")
    repo = root / "repo"

    subprocess.run(
        ["git", "init", "-b", "fixture-bootstrap", str(repo)],
        check=True,
        capture_output=True,
    )
    subprocess.run(
        ["git", "fast-import", "--quiet"],
        cwd=repo,
        input=fixture_stream(),
        check=True,
        capture_output=True,
    )
    git(repo, "config", "user.name", "Forkstack Fixture")
    git(repo, "config", "user.email", "fixture@example.com")
    git(repo, "remote", "add", "origin", str(root / "remote.git"))
    git(repo, "switch", "fs-head/gamma/3")
    return repo


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "path",
        nargs="?",
        type=Path,
        default=DEFAULT_FIXTURE,
        help=f"fixture directory to create (default: {DEFAULT_FIXTURE})",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="recreate an existing generated fixture",
    )
    args = parser.parse_args()

    try:
        repo = create_fixture(args.path, force=args.force)
    except RuntimeError as error:
        parser.error(str(error))

    print(f"Created fixture repository at {repo}")
    manifest = Path(__file__).resolve().parents[1] / "ui" / "Cargo.toml"
    print(f"Run: cargo run --manifest-path {manifest} -- --repo {repo}")


if __name__ == "__main__":
    main()
